### ISSUE TITLE
abandoned?

### ISSUE THREAD

**Issue by chadfurman** [robocoder/rips-scanner#4]
Hi, this project is now abandoned?  How to live?

Best Regards,
a Developer

**Comment by robocoder** [comment]
This is just a mirror for posterity. AFAIK it is being rewritten but it's successor may be closed source.

**Comment by robocoder** [comment]
I forgot there was a pull request. I'll review and merge into a `community` branch.

**Comment by shadesoflight** [comment]
A community version of RIPS for continued development would be great.

Maybe a "this is where I left off... this is what was going to be next... these are the caveats..." similar to the whitepaper http://www.php-security.org/downloads/rips.pdf

Thank you for your effort!

**Comment by ripsscanner** [comment]
The next generation is available at https://www.ripstech.com as commercial product (both cloud and standalone solution)

**Comment by shayneoneill** [comment]
Well that sucks :(
