### ISSUE TITLE
Scannning laravel App just stuck at 38%

### ISSUE THREAD

**Issue by im-noob** [robocoder/rips-scanner#6]
im just scanning my laravel app for security reasons...
using laravel 5.6
![capture](https://user-images.githubusercontent.com/32417365/37872067-9a0bcdb0-301c-11e8-9136-13d6da3b634b.PNG)

when i just reach at 39% it get stuck at 
scanning ...C:\....\vendor\mockery\mockery\tests\Mockery\Fixtures\SemiReservedWordsAsMethods.php (tokenizing)

why this is ??
![capture](https://user-images.githubusercontent.com/32417365/37872071-aec2f06c-301c-11e8-9933-41ae6a93c45e.PNG)

**Comment by robocoder** [comment]
It's stuck in a loop when it hits this line:
```
    function while() {}
```

**Comment by robocoder** [comment]
Reduced it to this minimal test case:
```
<?php
class SemiReservedWordsAsMethods
{
    function do() {} 
    function while() {}
}
```
