### ISSUE TITLE
running this on mac giving  fatal error

### ISSUE THREAD

**Issue by chetanbothra** [robocoder/rips-scanner#8]
OS: Mac OS 11.2.2 ( M1 Chip)
Php Versions : 8.x as well as php 7.4

Folder permission tried with 777 too. 
Same setup Works on ubuntu

![Screenshot 2021-12-31 at 1 53 39 PM](https://user-images.githubusercontent.com/13346364/147812094-6788fdaa-64d7-41ad-8763-f48a3ec940a1.png)

**Comment by robocoder** [comment]
Fixed by 41d2323
